import {
  LayoutDashboard,
  IdCard,
  CalendarClock,
  Wallet,
  Users,
  Building2,
  Briefcase,
  Award,
  Layers,
  Network,
  CalendarCheck,
  CalendarDays,
  Clock,
  Timer,
  MapPin,
  UserCheck,
  UserX,
  Repeat,
  Activity,
  BadgeCheck,
  Target,
  Milestone,
  Ban,
  HandCoins,
  Shield,
  FileText,
  Percent,
  Scale,
  TrendingUp,
  Receipt,
  Plane,
  Car,
  Kanban,
  MessagesSquare,
  FileSignature,
  ClipboardList,
  UserPlus,
  GitBranch,
  Star,
  LineChart,
  DoorOpen,
  ArrowRightLeft,
  Flag,
  Sparkles,
  GraduationCap,
  BarChart3,
  Settings,
  UserCog,
  Coins,
  BookOpen,
  SlidersHorizontal,
  ClipboardCheck,
  Mail,
  HeartPulse,
  History,
  Wrench,
  Banknote,
  ListChecks,
  Calculator,
  Bell,
  KeyRound,
  type LucideIcon,
} from "lucide-react";

export type NavItem = {
  title: string;
  href: string;
  icon: LucideIcon;
  badge?: string;
};

export type NavSection = {
  label: string;
  items: NavItem[];
};

// Sidebar information architecture — mirrors the Frappe HR workspace set
// (HR Setup, Shift & Attendance, Leaves, Payroll, Expenses, Recruitment,
// Performance, Tenure, Tax & Benefits, Reports).
export const navSections: NavSection[] = [
  {
    label: "Overview",
    items: [{ title: "Dashboard", href: "/dashboard", icon: LayoutDashboard }],
  },
  {
    label: "Employee (Self-Service)",
    items: [
      { title: "My Profile", href: "/profile", icon: IdCard },
      { title: "My Attendance", href: "/my-attendance", icon: CalendarClock },
      { title: "My Salary Slips", href: "/payroll/slips", icon: Wallet },
      { title: "My Timesheets", href: "/attendance/my-timesheets", icon: ClipboardList },
      { title: "My Expense Claims", href: "/my-claims", icon: Receipt },
      { title: "My Advances", href: "/my-advance", icon: HandCoins },
      { title: "Notifications", href: "/notifications", icon: Bell, badge: "2" },
      { title: "Change Password", href: "/change-password", icon: KeyRound },
    ],
  },
  {
    label: "Human Resources",
    items: [
      { title: "Employees", href: "/employees", icon: Users },
      { title: "Departments", href: "/departments", icon: Building2 },
      { title: "Designations", href: "/designations", icon: Briefcase },
      { title: "Employment Types", href: "/employment-types", icon: Briefcase },
      { title: "Employee Grades", href: "/employee-grades", icon: Award },
      { title: "Employee Groups", href: "/employee-groups", icon: Layers },
      { title: "Branches", href: "/branches", icon: GitBranch },
      { title: "Company", href: "/company", icon: Building2 },
      { title: "Organizational Chart", href: "/org-chart", icon: Network },
    ],
  },
  {
    label: "Shift & Attendance",
    items: [
      { title: "Attendance", href: "/attendance", icon: CalendarCheck },
      { title: "Mark Attendance", href: "/attendance/mark-attendance", icon: ClipboardCheck },
      { title: "Shift Assignment Tool", href: "/attendance/shift-assignment-tool", icon: Wrench },
      { title: "Daily Work Summary", href: "/attendance/daily-work-summary", icon: Mail },
      { title: "Roster", href: "/attendance/roster", icon: CalendarDays },
      { title: "Employee Checkin", href: "/attendance/checkin", icon: Clock },
      { title: "Shift Types", href: "/attendance/shift-types", icon: Timer },
      { title: "Shift Locations", href: "/attendance/shift-locations", icon: MapPin },
      { title: "Shift Schedules", href: "/attendance/shift-schedules", icon: Repeat },
      { title: "Shift Assignments", href: "/attendance/shift-assignments", icon: UserCog },
      { title: "Shift Requests", href: "/attendance/shift-requests", icon: Activity },
      { title: "Attendance Requests", href: "/attendance/attendance-requests", icon: UserCheck },
      { title: "Compensatory Leave", href: "/attendance/compensatory-leave", icon: UserX },
      { title: "Overtime Types", href: "/attendance/overtime-types", icon: Percent },
      { title: "Overtime Slips", href: "/attendance/overtime-slips", icon: TrendingUp },
      { title: "Timesheets", href: "/attendance/timesheets", icon: ClipboardList },
    ],
  },
  {
    label: "Leaves",
    items: [
      { title: "Leave Applications", href: "/leave", icon: CalendarDays },
      { title: "My Leave Balances", href: "/leave/balances", icon: Wallet },
      { title: "Apply Leave", href: "/leave/apply", icon: Plane },
      { title: "Approvals", href: "/leave/approvals", icon: BadgeCheck, badge: "3" },
      { title: "Leave Types", href: "/leave/types", icon: Layers },
      { title: "Leave Ledger", href: "/leave/ledger", icon: BookOpen },
      { title: "Leave Adjustment", href: "/leave/adjustment", icon: SlidersHorizontal },
      { title: "Earned Leave Schedule", href: "/leave/earned-leave-schedule", icon: CalendarClock },
      { title: "Leave Allocation", href: "/leave/allocations", icon: UserCheck },
      { title: "Leave Period", href: "/leave/periods", icon: CalendarClock },
      { title: "Leave Policy", href: "/leave/policies", icon: Shield },
      { title: "Policy Assignment", href: "/leave/policy-assignments", icon: UserCog },
      { title: "Holiday List", href: "/leave/holidays", icon: CalendarCheck },
      { title: "Leave Block List", href: "/leave/block-list", icon: Ban },
      { title: "Leave Encashment", href: "/leave/encashment", icon: HandCoins },
      { title: "Leave Control Panel", href: "/leave/control-panel", icon: Target },
    ],
  },
  {
    label: "Payroll",
    items: [
      { title: "Salary Structures", href: "/payroll", icon: Wallet },
      { title: "Salary Components", href: "/payroll/components", icon: Coins },
      { title: "Structure Assignment", href: "/payroll/assignments", icon: UserCog },
      { title: "Bulk Assignment", href: "/payroll/bulk-assignment", icon: Layers },
      { title: "Salary Slips", href: "/payroll/slips", icon: Receipt },
      { title: "Payroll Entry", href: "/payroll/processing", icon: LineChart },
      { title: "Additional Salary", href: "/payroll/additional-salary", icon: TrendingUp },
      { title: "Employee Advance", href: "/payroll/advances", icon: HandCoins },
      { title: "Salary Withholding", href: "/payroll/withholding", icon: Shield },
      { title: "Withholding Cycles", href: "/payroll/withholding-cycles", icon: Repeat },
      { title: "Arrears", href: "/payroll/arrears", icon: History },
      { title: "Payroll Correction", href: "/payroll/correction", icon: Wrench },
      { title: "Other Income", href: "/payroll/other-income", icon: Banknote },
      { title: "Taxable Salary Slabs", href: "/payroll/taxable-slabs", icon: ListChecks },
      { title: "Payroll Period", href: "/payroll/periods", icon: CalendarClock },
      { title: "Income Tax Slabs", href: "/payroll/tax-slabs", icon: Percent },
      { title: "Cost Centers", href: "/payroll/cost-centers", icon: Building2 },
      { title: "Retention Bonus", href: "/payroll/retention-bonus", icon: Award },
      { title: "Employee Incentives", href: "/payroll/incentives", icon: Star },
      { title: "Gratuity", href: "/payroll/gratuity", icon: Scale },
    ],
  },
  {
    label: "Expenses",
    items: [
      { title: "Expense Claims", href: "/expenses", icon: Receipt },
      { title: "New Claim", href: "/expenses/new", icon: Plane },
      { title: "Approvals", href: "/expenses/approvals", icon: BadgeCheck, badge: "2" },
      { title: "Expense Claim Types", href: "/expenses/types", icon: Layers },
      { title: "Full & Final Statement", href: "/expenses/full-and-final", icon: Calculator },
      { title: "Vehicle Service", href: "/expenses/vehicle-service", icon: Wrench },
      { title: "Travel Requests", href: "/expenses/travel-requests", icon: Car },
      { title: "Vehicle Logs", href: "/expenses/vehicle-logs", icon: MapPin },
    ],
  },
  {
    label: "Recruitment",
    items: [
      { title: "Job Openings", href: "/recruitment/jobs", icon: Briefcase },
      { title: "Job Applicants", href: "/recruitment/applications", icon: Users },
      { title: "Hiring Pipeline", href: "/recruitment/pipeline", icon: Kanban },
      { title: "Interviews", href: "/recruitment/interviews", icon: MessagesSquare },
      { title: "Job Offers", href: "/recruitment/offers", icon: FileSignature },
      { title: "Appointment Letters", href: "/recruitment/appointment-letters", icon: FileText },
      { title: "Job Requisitions", href: "/recruitment/requisitions", icon: ClipboardList },
      { title: "Staffing Plans", href: "/recruitment/staffing-plans", icon: Target },
      { title: "Employee Referrals", href: "/recruitment/referrals", icon: UserPlus },
    ],
  },
  {
    label: "Performance",
    items: [
      { title: "Appraisals", href: "/performance/appraisals", icon: Target },
      { title: "Appraisal Cycles", href: "/performance/cycles", icon: CalendarClock },
      { title: "Appraisal Templates", href: "/performance/templates", icon: FileText },
      { title: "KRA", href: "/performance/kra", icon: Milestone },
      { title: "Goals", href: "/performance/goals", icon: Activity },
      { title: "Promotions", href: "/performance/promotions", icon: TrendingUp },
      { title: "Performance Feedback", href: "/performance/feedback", icon: MessagesSquare },
    ],
  },
  {
    label: "Tenure",
    items: [
      { title: "Employee Onboarding", href: "/tenure/onboarding", icon: UserPlus },
      { title: "Employee Separation", href: "/tenure/separations", icon: DoorOpen },
      { title: "Exit Interviews", href: "/tenure/exit-interviews", icon: MessagesSquare },
      { title: "Transfers", href: "/tenure/transfers", icon: ArrowRightLeft },
      { title: "Grievances", href: "/tenure/grievances", icon: Flag },
      { title: "Skill Maps", href: "/tenure/skill-maps", icon: Sparkles },
      { title: "Employee Skills", href: "/tenure/skills", icon: Star },
      { title: "Training Records", href: "/tenure/training-records", icon: GraduationCap },
      { title: "Training Programs", href: "/tenure/training-programs", icon: GraduationCap },
      { title: "Training Events", href: "/tenure/training-events", icon: CalendarDays },
    ],
  },
  {
    label: "Tax & Benefits",
    items: [
      { title: "Exemption Declarations", href: "/tax-benefits/declarations", icon: FileText },
      { title: "Exemption Proof Submission", href: "/tax-benefits/proofs", icon: FileSignature },
      { title: "Benefit Applications", href: "/tax-benefits/benefit-applications", icon: ClipboardList },
      { title: "Benefit Claims", href: "/tax-benefits/benefit-claims", icon: HandCoins },
      { title: "Benefit Ledger", href: "/tax-benefits/benefit-ledger", icon: BookOpen },
      { title: "Health Insurance", href: "/tax-benefits/health-insurance", icon: HeartPulse },
    ],
  },
  {
    label: "Reports",
    items: [{ title: "Reports", href: "/reports", icon: BarChart3 }],
  },
  {
    label: "System",
    items: [{ title: "Settings", href: "/settings", icon: Settings }],
  },
];
