"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowUpRight, CheckCheck, ChevronRight, Copy, Eye, GitBranch, Link2, MessageSquare, Plus, Send, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { SearchSelect } from "@/components/shared/search-select";
import { runTaskCommand } from "@/hooks/use-task-workspace";
import { blockedBy, canEditTask, emptyTask, formatTaskDate, isClosed, personName } from "@/lib/tasks/domain";
import { canManageNode, canSeeList, canWriteWorkspace, fieldsFor, listArchived, preferencesFor, scopeLists, statusesFor, taskDraft } from "@/lib/tasks/workspace-model";
import { TASK_PRIORITIES, TASK_TYPES, type TaskDraft } from "@/lib/tasks/types";
import type { ChecklistItem, FieldValue, WorkField, WorkScope, WorkspaceState, WorkspaceTask } from "@/lib/tasks/workspace-types";
import { WorkEmpty, WorkLabel, WorkMenu, WorkModal, WorkPeople, WorkStatusBadge, OrderButtons } from "./common";
import { TaskDateInput } from "../task-shared";

export function CustomFieldInput({ field, value, onChange, disabled = false }: { field: WorkField; value: FieldValue; onChange: (value: FieldValue) => void; disabled?: boolean }) {
  if (field.type === "checkbox") return <Checkbox aria-label={field.name} checked={value === true} disabled={disabled} onCheckedChange={(v) => onChange(!!v)} />;
  if (field.type === "select") return <SearchSelect disabled={disabled} value={String(value ?? "")} options={field.options.map((o) => ({ value: o.id, label: o.label }))} onChange={onChange} placeholder={field.name} />;
  return <Input disabled={disabled} aria-label={field.name} type={field.type === "number" ? "number" : field.type === "date" ? "date" : "text"} defaultValue={String(value ?? "")} key={`${field.id}-${value}`} onBlur={(e) => { const v = e.target.value; const next = field.type === "number" ? v === "" ? null : Number(v) : v; if (next !== value) onChange(next); }} onKeyDown={(e) => { if (e.key === "Enter") e.currentTarget.blur(); }} />;
}
export function QuickTask({ state, scope, onClose, onCreated, listId = "", parentId = "", statusId = "", dueAt = null }: { state: WorkspaceState; scope: WorkScope; onClose: () => void; onCreated: (id: string) => void; listId?: string; parentId?: string; statusId?: string; dueAt?: string | null }) {
  const lists = scopeLists(state, scope).filter((l) => canWriteWorkspace(state, l.workspaceId));
  const initialList = lists.find((l) => l.id === listId) ?? (scope.kind === "list" ? lists[0] : lists.length === 1 ? lists[0] : undefined);
  const [draft, setDraft] = useState<TaskDraft>(() => ({ ...emptyTask(initialList), parentId, dueAt }));
  const [status, setStatus] = useState(statusId);
  const [id] = useState(() => crypto.randomUUID());
  const list = lists.find((l) => l.id === draft.projectId);
  const work = state.workspaces.find((w) => w.id === scope.workspaceId)!;
  const change = (patch: Partial<TaskDraft>) => setDraft({ ...draft, ...patch });
  return <WorkModal title={parentId ? "Add subtask" : "Create task"} description="Start with an outcome. Add the details as your work takes shape." onClose={() => { if (!draft.subject.trim() || window.confirm("Discard this new task?")) onClose(); }}>
    {!lists.length ? <WorkEmpty title="Create a List first" description="Tasks need a List and a team to belong to." /> : <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (runTaskCommand({ kind: "work-task", id, draft, statusId: status || undefined }, "Task created")) { onClose(); onCreated(id); } }}>
      <SearchSelect value={draft.projectId} disabled={!!parentId} options={lists.map((l) => ({ value: l.id, label: l.name }))} placeholder="Choose a destination List" onChange={(id) => { const next = lists.find((l) => l.id === id); setDraft({ ...emptyTask(next), subject: draft.subject, description: draft.description }); setStatus(""); }} />
      <Input aria-label="Task name" required autoFocus maxLength={255} className="text-base font-medium" placeholder="What needs to be done?" value={draft.subject} onChange={(e) => change({ subject: e.target.value })} />
      <Textarea aria-label="Description" rows={3} placeholder="Add a description…" value={draft.description} onChange={(e) => change({ description: e.target.value })} />
      <div className="grid gap-3 sm:grid-cols-2"><WorkLabel label="Status"><SearchSelect value={status || statusesFor(state, draft.projectId).find((s) => s.category === "Open")?.id || ""} options={statusesFor(state, draft.projectId).map((s) => ({ value: s.id, label: s.name }))} onChange={setStatus} /></WorkLabel><WorkLabel label="Priority"><SearchSelect value={draft.priority} options={TASK_PRIORITIES} onChange={(v) => v && change({ priority: v as TaskDraft["priority"] })} /></WorkLabel><WorkLabel label="Assignees"><SearchSelect multiple value={draft.assigneeIds} options={state.people.filter((p) => list?.memberIds.includes(p.id)).map((p) => ({ value: p.id, label: p.name }))} onChange={(assigneeIds) => change({ assigneeIds })} placeholder="Choose assignees" /></WorkLabel><WorkLabel label={`Due · ${work.timezone}`}><TaskDateInput id="quick-task-due" value={draft.dueAt} timezone={work.timezone} onChange={(dueAt) => change({ dueAt })} /></WorkLabel></div>
      <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" disabled={!draft.subject.trim() || !list}><Plus className="size-4" />Create task</Button></div>
    </form>}
  </WorkModal>;
}
export function TaskMoveDialog({ state, ids, onClose }: { state: WorkspaceState; ids: string[]; onClose: () => void }) {
  const first = state.tasks.find((t) => t.id === ids[0])!;
  const workspaceId = state.lists.find((l) => l.id === first.listId)!.workspaceId;
  const [listId, setListId] = useState("");
  const [statusMap, setStatusMap] = useState<Record<string, string>>({});
  const [assignees, setAssignees] = useState(first.assigneeIds);
  const selected = new Set(ids); let more = true;
  while (more) { more = false; for (const t of state.tasks) if (selected.has(t.parentId) && !selected.has(t.id)) { selected.add(t.id); more = true; } }
  const tasks = state.tasks.filter((t) => selected.has(t.id));
  const target = state.lists.find((l) => l.id === listId);
  const oldStatuses = [...new Set(tasks.map((t) => t.statusId))];
  return <WorkModal title={`Move ${tasks.length} task${tasks.length === 1 ? "" : "s"}`} description="Descendants move with their parent. An individually moved subtask is detached. List-specific custom fields must be cleared or migrated before moving." onClose={onClose}><div className="space-y-4"><SearchSelect value={listId} options={state.lists.filter((l) => l.workspaceId === workspaceId && !listArchived(state, l) && canManageNode(state, l)).map((l) => ({ value: l.id, label: l.name }))} onChange={(id) => { setListId(id); setStatusMap({}); }} placeholder="Destination List" />{target && <><WorkLabel label="Assignments after move"><SearchSelect multiple value={assignees} options={state.people.filter((p) => target.memberIds.includes(p.id)).map((p) => ({ value: p.id, label: p.name }))} onChange={setAssignees} /></WorkLabel>{oldStatuses.map((id) => { const task = tasks.find((t) => t.statusId === id)!; return <WorkLabel key={id} label={`Map ${statusesFor(state, task.listId).find((s) => s.id === id)?.name}`}><SearchSelect value={statusMap[id] ?? ""} options={statusesFor(state, listId).filter((s) => s.category === task.status).map((s) => ({ value: s.id, label: s.name }))} onChange={(value) => setStatusMap({ ...statusMap, [id]: value })} /></WorkLabel>; })}</>}<Button className="w-full" disabled={!target || oldStatuses.some((id) => !statusMap[id])} onClick={() => { if (runTaskCommand({ kind: "work-move", ids, listId, statusMap, assigneeIds: assignees }, "Tasks moved")) onClose(); }}>Move tasks</Button></div></WorkModal>;
}

export function WorkspaceTaskDetail({ state, id, onOpen, onClose, fullPage = false }: { state: WorkspaceState; id: string; onOpen: (id: string) => void; onClose: () => void; fullPage?: boolean }) {
  const task = state.tasks.find((t) => t.id === id);
  const list = state.lists.find((l) => l.id === task?.listId);
  if (!task || !list || !canSeeList(state, list)) return <WorkEmpty title="Task unavailable" description="This task may be missing or outside the current demo member's access." action={<Button variant="outline" onClick={onClose}>Go back</Button>} />;
  return <TaskContent key={`${id}-${state.actorId}`} state={state} task={task} onOpen={onOpen} onClose={onClose} fullPage={fullPage} />;
}
function TaskContent({ state, task, onOpen, onClose, fullPage }: { state: WorkspaceState; task: WorkspaceTask; onOpen: (id: string) => void; onClose: () => void; fullPage: boolean }) {
  const list = state.lists.find((l) => l.id === task.listId)!;
  const work = state.workspaces.find((w) => w.id === list.workspaceId)!;
  const [addSubtask, setAddSubtask] = useState(false);
  const [moving, setMoving] = useState(false);
  const [checkTitle, setCheckTitle] = useState("");
  const [resource, setResource] = useState({ name: "", url: "" });
  const [reply, setReply] = useState("");
  const [editingComment, setEditingComment] = useState("");
  const [mentions, setMentions] = useState<string[]>([]);
  const pref = preferencesFor(state, work.id);
  const draftKey = `task:${task.id}`;
  const commentKey = `comment:${task.id}`;
  let text = { subject: task.subject, description: task.description };
  try { if (pref.drafts[draftKey]) text = JSON.parse(pref.drafts[draftKey]); } catch { /* Ignore only malformed draft text; the task itself is unchanged. */ }
  const comment = pref.drafts[commentKey] ?? "";
  const stash = (key: string, value: string) => runTaskCommand({ kind: "work-preferences", workspaceId: work.id, patch: { drafts: { ...pref.drafts, [key]: value } } });
  const editable = canEditTask(state, task) && !isClosed(task) && !task.archived && !listArchived(state, list);
  const save = (patch: Partial<TaskDraft>, extra: { checklist?: ChecklistItem[]; fields?: WorkspaceTask["fields"]; resources?: WorkspaceTask["resources"] } = {}) => runTaskCommand({ kind: "work-task", id: task.id, draft: { ...taskDraft(task), ...patch }, ...extra }, "Task updated");
  const children = state.tasks.filter((t) => t.parentId === task.id);
  const dependencies = blockedBy(state, task);
  const personOptions = state.people.filter((p) => list.memberIds.includes(p.id)).map((p) => ({ value: p.id, label: `${p.name} · ${p.employeeCode}` }));
  const comments = state.comments.filter((c) => c.taskId === task.id);
  const activity = state.activities.filter((a) => a.taskId === task.id).slice(-20).reverse();
  const dirty = text.subject !== task.subject || text.description !== task.description;
  const copyLink = async () => { try { await navigator.clipboard.writeText(`${location.origin}/workspaces/${work.id}/tasks/${task.id}`); toast.success("Local demo link copied"); } catch { toast.error("Clipboard unavailable"); } };
  const reorderCheck = (index: number, delta: number) => { const checklist = [...task.checklist]; [checklist[index], checklist[index + delta]] = [checklist[index + delta], checklist[index]]; save({}, { checklist }); };
  return <div className="flex h-full min-h-0 flex-col bg-card">
    <header className="flex shrink-0 items-center gap-2 border-b px-5 py-3"><span className="truncate text-xs text-muted-foreground">{state.spaces.find((s) => s.id === list.spaceId)?.name}</span><ChevronRight className="size-3 shrink-0 text-muted-foreground" /><Link href={`/workspaces/${work.id}/lists/${list.id}`} className="truncate text-xs font-medium">{list.name}</Link><div className="ml-auto flex shrink-0 items-center gap-1"><Button variant="ghost" size="icon-sm" aria-label="Copy task link" onClick={copyLink}><Link2 className="size-4" /></Button>{!fullPage && <Button variant="ghost" size="icon-sm" aria-label="Open task full page" nativeButton={false} render={<Link href={`/workspaces/${work.id}/tasks/${task.id}`} />}><ArrowUpRight className="size-4" /></Button>}<Button variant="ghost" size="icon-sm" aria-label="Close task" onClick={onClose}><X className="size-4" /></Button></div></header>
    <div className="grid min-h-0 flex-1 overflow-y-auto lg:grid-cols-[minmax(0,1fr)_320px] lg:overflow-hidden">
      <section className="min-w-0 space-y-6 p-5 lg:overflow-y-auto lg:p-7">
        <div className="flex items-center gap-2"><Badge variant="outline" className="text-[10px]">{task.code}</Badge>{task.archived && <Badge variant="secondary">Archived</Badge>}<WorkStatusBadge state={state} task={task} /><div className="ml-auto flex"><Button variant="ghost" size="icon-sm" aria-label={task.watcherIds.includes(state.actorId) ? "Stop watching" : "Watch task"} className={task.watcherIds.includes(state.actorId) ? "text-primary" : ""} onClick={() => runTaskCommand({ kind: "work-watch", id: task.id })}><Eye className="size-4" /></Button><WorkMenu actions={[{ label: pref.favorites.includes(task.id) ? "Remove favorite" : "Add to favorites", onClick: () => runTaskCommand({ kind: "work-preferences", workspaceId: work.id, patch: { favorites: pref.favorites.includes(task.id) ? pref.favorites.filter((id) => id !== task.id) : [...pref.favorites, task.id] } }) }, { label: "Move to another List", disabled: !canManageNode(state, list), onClick: () => setMoving(true) }, { label: "Duplicate with subtasks", icon: <Copy className="size-3.5" />, disabled: !canEditTask(state, task), onClick: () => runTaskCommand({ kind: "work-duplicate", id: task.id }, "Task duplicated") }, { label: task.archived ? "Restore task" : "Archive task", danger: !task.archived, disabled: !canManageNode(state, list), onClick: () => { if (window.confirm(`${task.archived ? "Restore" : "Archive"} this task? Its history will be preserved.`)) runTaskCommand({ kind: "work-bulk", ids: [task.id], patch: {}, archived: !task.archived }); } }]} /></div></div>
        <Input aria-label="Task title" disabled={!editable} value={text.subject} onChange={(e) => stash(draftKey, JSON.stringify({ ...text, subject: e.target.value }))} className="h-auto border-0 bg-transparent px-0 py-0 text-xl! font-semibold tracking-tight shadow-none" />
        {task.parentId && <Button variant="link" className="h-auto p-0 text-xs" onClick={() => onOpen(task.parentId)}><GitBranch className="size-3" />{state.tasks.find((t) => t.id === task.parentId)?.subject}</Button>}
        {dependencies.length > 0 && <div className="flex items-center gap-2 rounded-lg bg-amber-500/10 p-3 text-xs text-amber-700 dark:text-amber-300"><GitBranch className="size-4" />Blocked by {dependencies.length} unfinished {dependencies.length === 1 ? "dependency" : "dependencies"}</div>}
        <div className="grid gap-x-6 gap-y-4 sm:grid-cols-2">
          <WorkLabel label="Status"><SearchSelect value={task.statusId} disabled={!canWriteWorkspace(state, work.id) || task.archived} options={statusesFor(state, list.id).map((s) => ({ value: s.id, label: s.name }))} onChange={(id) => { if (!id) return; const next = statusesFor(state, list.id).find((s) => s.id === id); if (next?.category === "Cancelled" && !window.confirm("Cancel this task? Dependencies will treat it as resolved.")) return; runTaskCommand({ kind: "work-status", ids: [task.id], statusIds: { [task.id]: id } }, "Status updated"); }} /></WorkLabel>
          <WorkLabel label="Assignees"><SearchSelect multiple disabled={!editable} value={task.assigneeIds} options={personOptions} placeholder="Assign people" onChange={(assigneeIds) => save({ assigneeIds })} /></WorkLabel>
          <WorkLabel label="Priority"><SearchSelect disabled={!editable} value={task.priority} options={TASK_PRIORITIES} onChange={(value) => value && save({ priority: value as TaskDraft["priority"] })} /></WorkLabel>
          <WorkLabel label="Type"><SearchSelect disabled={!editable} value={task.type} options={TASK_TYPES} onChange={(type) => type && save({ type })} /></WorkLabel>
          <WorkLabel label={`Start · ${work.timezone}`}><fieldset disabled={!editable}><TaskDateInput id={`start-${task.id}`} value={task.startAt} timezone={work.timezone} onChange={(startAt) => save({ startAt })} /></fieldset></WorkLabel>
          <WorkLabel label="Due"><fieldset disabled={!editable}><TaskDateInput id={`due-${task.id}`} value={task.dueAt} timezone={work.timezone} onChange={(dueAt) => save({ dueAt })} /></fieldset></WorkLabel>
          <WorkLabel label="Estimated hours"><Input disabled={!editable} type="number" min={0} step={0.5} defaultValue={task.estimateHours} key={`estimate-${task.estimateHours}`} onBlur={(e) => Number(e.target.value) !== task.estimateHours && save({ estimateHours: Number(e.target.value) })} /></WorkLabel>
          <WorkLabel label="Progress"><div className="flex items-center gap-3"><Progress value={task.progress} className="h-1.5" /><Input aria-label="Progress percent" className="w-20" disabled={!editable} type="number" min={0} max={100} defaultValue={task.progress} key={`progress-${task.progress}`} onBlur={(e) => Number(e.target.value) !== task.progress && save({ progress: Number(e.target.value) })} /></div></WorkLabel>
          <WorkLabel label="Reviewer"><SearchSelect disabled={!editable} value={task.reviewerId} options={personOptions} onChange={(reviewerId) => save({ reviewerId })} /></WorkLabel><WorkLabel label="Approval"><label className="flex h-9 items-center gap-2 text-xs"><Checkbox checked={task.reviewRequired} disabled={!editable} onCheckedChange={(v) => save({ reviewRequired: !!v })} />Review required before completion</label></WorkLabel>
        </div>
        <WorkLabel label="Description"><Textarea disabled={!editable} value={text.description} rows={5} placeholder="Add context, requirements, or a definition of done…" onChange={(e) => stash(draftKey, JSON.stringify({ ...text, description: e.target.value }))} className="resize-y border-0 bg-muted/50 text-sm" />{dirty && <div className="flex items-center gap-2"><Button size="sm" onClick={() => { if (save(text)) stash(draftKey, ""); }}>Save changes</Button><Button size="sm" variant="ghost" onClick={() => stash(draftKey, "")}>Discard</Button><span className="text-[10px] text-muted-foreground">Draft saved in this browser</span></div>}</WorkLabel>
        <WorkLabel label="Tags"><Input disabled={!editable} defaultValue={task.tags.join(", ")} key={`tags-${task.tags.join()}`} placeholder="Separate tags with commas" onBlur={(e) => { const tags = e.target.value.split(",").map((s) => s.trim()).filter(Boolean); if (tags.join() !== task.tags.join()) save({ tags }); }} /></WorkLabel>
        {!!fieldsFor(state, list.id).length && <div className="space-y-3 border-t pt-5"><h3 className="text-sm font-semibold">Custom fields</h3><div className="grid gap-3 sm:grid-cols-2">{fieldsFor(state, list.id).map((f) => <WorkLabel key={f.id} label={f.name}><CustomFieldInput field={f} value={task.fields[f.id] ?? null} disabled={!editable} onChange={(value) => save({}, { fields: { ...task.fields, [f.id]: value } })} /></WorkLabel>)}</div></div>}
        <section className="space-y-3 border-t pt-5"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-sm font-semibold"><GitBranch className="size-4 text-muted-foreground" />Subtasks <Badge variant="secondary">{children.length}</Badge></h3><Button size="sm" variant="ghost" disabled={!editable} onClick={() => setAddSubtask(true)}><Plus className="size-3.5" />Add</Button></div>{children.map((child) => <div key={child.id} className="flex items-center gap-3 border-b py-2"><WorkStatusBadge state={state} task={child} /><Button variant="link" className="h-auto flex-1 justify-start whitespace-normal p-0 text-left text-xs" onClick={() => onOpen(child.id)}>{child.subject}</Button><WorkPeople state={state} ids={child.assigneeIds} /></div>)}{!children.length && <p className="text-xs text-muted-foreground">Break this outcome into smaller pieces of work.</p>}</section>
        <section className="space-y-3 border-t pt-5"><h3 className="flex items-center gap-2 text-sm font-semibold"><CheckCheck className="size-4 text-muted-foreground" />Checklist <span className="text-xs font-normal text-muted-foreground">{task.checklist.filter((i) => i.done).length}/{task.checklist.length}</span></h3>{task.checklist.map((item, index) => <div key={item.id} className="space-y-1"><div className="flex items-center gap-2"><Checkbox aria-label={`Complete ${item.title}`} disabled={!editable} checked={item.done} onCheckedChange={(done) => save({}, { checklist: task.checklist.map((i) => i.id === item.id ? { ...i, done: !!done } : i) })} /><Input disabled={!editable} className={`h-8 flex-1 border-0 text-xs ${item.done ? "text-muted-foreground line-through" : ""}`} defaultValue={item.title} key={`${item.id}-${item.title}`} aria-label="Checklist item" onBlur={(e) => e.target.value !== item.title && save({}, { checklist: task.checklist.map((i) => i.id === item.id ? { ...i, title: e.target.value } : i) })} /><OrderButtons first={!editable || index === 0} last={!editable || index === task.checklist.length - 1} up={() => reorderCheck(index, -1)} down={() => reorderCheck(index, 1)} /><Button variant="ghost" size="icon-sm" disabled={!editable} aria-label="Remove checklist item" onClick={() => save({}, { checklist: task.checklist.filter((i) => i.id !== item.id) })}><X className="size-3" /></Button></div><div className="ml-6 max-w-60"><SearchSelect disabled={!editable} value={item.assigneeId} options={personOptions} placeholder="Assign checklist item" onChange={(assigneeId) => save({}, { checklist: task.checklist.map((i) => i.id === item.id ? { ...i, assigneeId } : i) })} /></div></div>)}{editable && <form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); if (checkTitle.trim() && save({}, { checklist: [...task.checklist, { id: crypto.randomUUID(), title: checkTitle.trim(), done: false, assigneeId: "" }] })) setCheckTitle(""); }}><Input value={checkTitle} onChange={(e) => setCheckTitle(e.target.value)} placeholder="Add a checklist item…" aria-label="New checklist item" /><Button variant="outline" type="submit" size="icon" aria-label="Add checklist item"><Plus className="size-4" /></Button></form>}</section>
        <section className="space-y-3 border-t pt-5"><h3 className="text-sm font-semibold">Dependencies</h3><SearchSelect multiple value={task.dependencyIds} disabled={!editable} options={state.tasks.filter((t) => t.id !== task.id && state.lists.some((l) => l.id === t.listId && l.workspaceId === work.id && canSeeList(state, l))).map((t) => ({ value: t.id, label: `${t.code} · ${t.subject}` }))} onChange={(dependencyIds) => save({ dependencyIds })} placeholder="Waiting on…" />{state.tasks.filter((t) => t.dependencyIds.includes(task.id) && state.lists.some((l) => l.id === t.listId && canSeeList(state, l))).map((t) => <Button variant="link" className="h-auto p-0 text-xs" key={t.id} onClick={() => onOpen(t.id)}>Unblocks: {t.subject}</Button>)}</section>
        <section className="space-y-3 border-t pt-5"><h3 className="text-sm font-semibold">Linked resources</h3>{task.resources.map((r) => <div key={r.id} className="flex items-center justify-between"><a href={r.url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-xs text-primary"><Link2 className="size-3" />{r.name}</a><Button disabled={!editable} variant="ghost" size="icon-sm" aria-label={`Remove ${r.name}`} onClick={() => save({}, { resources: task.resources.filter((item) => item.id !== r.id) })}><Trash2 className="size-3" /></Button></div>)}{editable && <form className="flex flex-wrap gap-2" onSubmit={(e) => { e.preventDefault(); if (save({}, { resources: [...task.resources, { id: crypto.randomUUID(), ...resource }] })) setResource({ name: "", url: "" }); }}><Input aria-label="Resource name" className="min-w-28 flex-1" required placeholder="Name" value={resource.name} onChange={(e) => setResource({ ...resource, name: e.target.value })} /><Input aria-label="Resource URL" className="min-w-40 flex-1" type="url" required placeholder="https://…" value={resource.url} onChange={(e) => setResource({ ...resource, url: e.target.value })} /><Button variant="outline" type="submit">Add link</Button></form>}<p className="text-[10px] text-muted-foreground">Links only in this demo. Files are not uploaded.</p></section>
        <p className="text-[10px] text-muted-foreground">Created by {personName(state, task.createdBy)} · {formatTaskDate(task.createdAt, work.timezone, true)}{task.completedAt && ` · Completed ${formatTaskDate(task.completedAt, work.timezone, true)}`}</p>
      </section>
      <aside className="flex min-h-96 flex-col border-t bg-muted/30 lg:min-h-0 lg:border-t-0 lg:border-l"><div className="flex items-center gap-2 border-b p-4 text-sm font-semibold"><MessageSquare className="size-4" />Activity & comments <span className="ml-auto text-xs font-normal text-muted-foreground">{comments.length}</span></div><div className="flex-1 space-y-4 overflow-y-auto p-4">{comments.map((c) => <article className={`space-y-2 ${c.parentId ? "ml-5 border-l-2 border-primary/20 pl-3" : ""}`} key={c.id}><div className="flex items-center gap-2"><WorkPeople state={state} ids={[c.actorId]} /><span className="text-xs font-medium">{personName(state, c.actorId)}</span><span className="ml-auto text-[9px] text-muted-foreground">{formatTaskDate(c.at, work.timezone)}</span></div>{c.parentId && <p className="truncate text-[10px] text-muted-foreground">Reply to {personName(state, comments.find((item) => item.id === c.parentId)?.actorId ?? "")}</p>}<p className={`whitespace-pre-wrap break-words text-xs leading-relaxed ${c.deleted ? "italic text-muted-foreground" : ""}`}>{c.body}</p>{!!c.mentions?.length && <p className="text-[10px] text-primary">{c.mentions.map((id) => `@${personName(state, id)}`).join(" ")}</p>}{!c.deleted && canWriteWorkspace(state, work.id) && <div className="flex gap-3"><Button variant="link" className="h-auto p-0 text-[10px]" onClick={() => { setReply(c.id); setEditingComment(""); }}>Reply</Button>{c.actorId === state.actorId && <><Button variant="link" className="h-auto p-0 text-[10px]" onClick={() => { setEditingComment(c.id); stash(commentKey, c.body); setMentions(c.mentions ?? []); }}>Edit</Button><Button variant="link" className="h-auto p-0 text-[10px] text-muted-foreground" onClick={() => { if (window.confirm("Remove your comment?")) runTaskCommand({ kind: "work-comment", taskId: task.id, id: c.id, body: "", mentions: [], deleted: true }); }}>Remove</Button></>}</div>}</article>)}<div className="space-y-3 border-t pt-4">{activity.map((a) => <div key={a.id} className="flex gap-2 text-[10px] leading-relaxed text-muted-foreground"><span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-border" /><p><span className="font-medium">{personName(state, a.actorId)}</span> {a.message}<span className="block opacity-70">{formatTaskDate(a.at, work.timezone, true)}</span></p></div>)}</div></div>
        {canWriteWorkspace(state, work.id) && <form className="space-y-2 border-t bg-card p-3" onSubmit={(e) => { e.preventDefault(); if (runTaskCommand({ kind: "work-comment", taskId: task.id, id: editingComment || undefined, body: comment, parentId: reply || undefined, mentions }, "Comment saved")) { stash(commentKey, ""); setReply(""); setEditingComment(""); setMentions([]); } }}>{(reply || editingComment) && <div className="flex items-center justify-between text-[10px] text-primary">{editingComment ? "Editing your comment" : "Replying to comment"}<Button variant="ghost" size="icon-sm" aria-label="Cancel reply" onClick={() => { setReply(""); setEditingComment(""); }}><X className="size-3" /></Button></div>}<Textarea value={comment} onChange={(e) => stash(commentKey, e.target.value)} placeholder="Write an update…" aria-label="Comment" rows={3} className="text-xs" /><SearchSelect multiple value={mentions} options={personOptions} onChange={setMentions} placeholder="Mention teammates" /><div className="flex items-center justify-between"><span className="text-[9px] text-muted-foreground">Drafts stay in this browser</span><Button size="sm" type="submit" disabled={!comment.trim()}><Send className="size-3" />{editingComment ? "Save" : "Post"}</Button></div></form>}
      </aside>
    </div>
    {addSubtask && <QuickTask state={state} scope={{ kind: "list", id: list.id, workspaceId: work.id }} listId={list.id} parentId={task.id} onClose={() => setAddSubtask(false)} onCreated={onOpen} />}
    {moving && <TaskMoveDialog state={state} ids={[task.id]} onClose={() => setMoving(false)} />}
  </div>;
}
